version: 2

sources:
  - name: northwind_dataset
    description: This is a replica of the Postgres database used by our app
    tables:
      - name: public_orders
        description: >
          One record per order. Includes cancelled and deleted orders.
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Id of the customer table
      - name: public_customers
        description: >
          This is the customers table
        columns:
          - name: customer_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: public_products
        description: >
          This is the customers table
        columns:
          - name: product_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: public_categories
        description: >
          This is the categorie table
        columns:
          - name: category_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: public_suppliers
        description: >
          This is the suppliers table
        columns:
          - name: supplier_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: public_shippers
        description: >
          This is the shippers table
        columns:
          - name: shipper_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: public_employees
        description: >
          This is the employees table
        columns:
          - name: employee_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
      - name: public_order_details
        description: >
          This is the order details table
        columns:
          - name: order_id
            description: Primary key of the orders table